-- =============================================================================
-- V1__init_schema.sql
-- BLT (Bio-Latency Tracker) — Initial schema baseline
-- Dialect: PostgreSQL 16
--
-- 원칙
--   1. 시간 컬럼은 모두 TIMESTAMPTZ. 앱은 UTC 저장 / KST 직렬화.
--   2. 식별자는 소문자, unquoted. ERD의 큰따옴표 제거.
--   3. 본 파일은 스키마(테이블/컬럼/기본값)만 정의. 제약·인덱스는 V2에서.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
                       id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       apple_sub_hash          VARCHAR(64)  NOT NULL,                          -- SHA-256(apple sub)
                       email                   VARCHAR(255),
                       nickname                VARCHAR(50),
                       status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',         -- ACTIVE | WITHDRAW_PENDING | WITHDRAWN
                       auth_type               VARCHAR(20)  NOT NULL,                          -- APPLE | GUEST
                       birth_year              SMALLINT,
                       gender                  VARCHAR(10),
                       avg_wake_time           TIME,
                       occupation              VARCHAR(30),
                       onboarding_completed    BOOLEAN      NOT NULL DEFAULT FALSE,
                       apns_device_token       VARCHAR(64),
                       notification_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
                       pvt_reminder_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
                       pvt_reminder_time       TIME         NOT NULL DEFAULT '09:00:00',        -- 사용자 개별 알림 시각
                       notification_timezone   VARCHAR(40)  NOT NULL DEFAULT 'Asia/Seoul',
                       created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
                       deleted_at              TIMESTAMPTZ                                      -- 탈퇴 시점 기록용 (status와 함께 운용)
);

COMMENT ON TABLE  users IS '서비스 사용자';
COMMENT ON COLUMN users.apple_sub_hash         IS 'Apple Sign-In sub 클레임의 SHA-256 해시. 원본 sub은 저장 금지';
COMMENT ON COLUMN users.status                 IS '계정 라이프사이클: ACTIVE → WITHDRAW_PENDING → WITHDRAWN';
COMMENT ON COLUMN users.auth_type              IS '인증 방식: APPLE | GUEST';
COMMENT ON COLUMN users.pvt_reminder_time      IS '사용자별 PVT 측정 리마인더 발송 시각 (notification_timezone 기준)';
COMMENT ON COLUMN users.notification_timezone  IS 'IANA 타임존 식별자. pvt_reminder_time 해석 기준';
COMMENT ON COLUMN users.deleted_at             IS '논리 삭제 시각. status=WITHDRAWN 과 함께 채워짐';


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. refresh_tokens
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE refresh_tokens (
                                id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id      BIGINT       NOT NULL,
                                token_hash   VARCHAR(64)  NOT NULL,                                       -- SHA-256(raw refresh token)
                                expires_at   TIMESTAMPTZ  NOT NULL,
                                revoked_at   TIMESTAMPTZ,
                                created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  refresh_tokens IS 'JWT refresh token 저장소. 회전(rotation) 방식.';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'raw token은 저장하지 않음. 비교는 SHA-256 hash 일치로';
COMMENT ON COLUMN refresh_tokens.revoked_at IS '회전 또는 로그아웃 시점';


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. consent_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE consent_logs (
                              id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id         BIGINT       NOT NULL,
                              consent_type    VARCHAR(30)  NOT NULL,                                    -- TOS | PRIVACY | HEALTH_DATA | MARKETING ...
                              policy_version  VARCHAR(10)  NOT NULL,                                    -- 약관 버전. 법적 분쟁 추적용
                              agreed          BOOLEAN      NOT NULL,
                              agreed_at       TIMESTAMPTZ  NOT NULL,
                              client_ip       INET                                                       -- 동의 시점의 IP. 법적 증빙
);

COMMENT ON TABLE  consent_logs IS '약관 동의 이력. 한 번 들어가면 수정 불가(append-only).';


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. user_devices
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_devices (
                              id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id         BIGINT       NOT NULL,
                              fcm_token       VARCHAR(255) NOT NULL,
                              platform        VARCHAR(10)  NOT NULL,                                    -- iOS | Android
                              device_model    VARCHAR(50),
                              app_version     VARCHAR(20),
                              os_version      VARCHAR(20),
                              last_active_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                              revoked_at      TIMESTAMPTZ,                                              -- 로그아웃 / FCM invalid token 반환 시
                              created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  user_devices IS '푸시 발송 대상 디바이스';
COMMENT ON COLUMN user_devices.last_active_at IS '비활성 토큰 정리(housekeeping)용';
COMMENT ON COLUMN user_devices.revoked_at     IS '로그아웃 / FCM이 invalid token 반환 시 채움';


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. notification_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE notification_logs (
                                   log_id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   user_id             BIGINT       NOT NULL,
                                   user_device_id      BIGINT,                                               -- 발송 대상 디바이스. 토큰 만료 등으로 NULL 가능
                                   notification_type   VARCHAR(30)  NOT NULL,                                -- PVT_REMINDER | ROI_READY | ...
                                   title               VARCHAR(255) NOT NULL,
                                   body                TEXT         NOT NULL,
                                   payload             JSONB        NOT NULL DEFAULT '{}'::jsonb,            -- deep link, score_id 등
                                   fcm_message_id      VARCHAR(255),                                         -- FCM 응답 message_id. 발송 시도 전엔 NULL
                                   status              VARCHAR(20)  NOT NULL,                                -- QUEUED | SENT | DELIVERED | FAILED | OPENED
                                   error_code          VARCHAR(50),
                                   error_message       TEXT,
                                   scheduled_at        TIMESTAMPTZ  NOT NULL,                                -- 발송 예정 시각
                                   sent_at             TIMESTAMPTZ,                                          -- 실제 FCM 전송 시각 (ERD 수정: NULL 허용)
                                   delivered_at        TIMESTAMPTZ,                                          -- 단말 배송 완료 시각 (ERD 오타 deliverd_at 수정)
                                   opened_at           TIMESTAMPTZ,                                          -- 사용자 오픈 시각
                                   created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  notification_logs IS '푸시 알림 발송 이력. 스케줄→전송→배송→오픈 단계별 시각 기록';
COMMENT ON COLUMN notification_logs.user_device_id  IS '발송 시점의 디바이스 참조. 디바이스 폐기 시 SET NULL';
COMMENT ON COLUMN notification_logs.payload         IS 'deep_link / score_id 등 클라이언트 처리용 데이터';
COMMENT ON COLUMN notification_logs.fcm_message_id  IS 'FCM 응답으로 받은 식별자';


-- ─────────────────────────────────────────────────────────────────────────────
-- 6. sleep_records
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE sleep_records (
                               id                       BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id                  BIGINT            NOT NULL,
                               sleep_date               DATE              NOT NULL,                     -- 수면이 끝난 날짜 (KST 기준)
                               total_minutes            INTEGER           NOT NULL,
                               deep_minutes             INTEGER,
                               rem_minutes              INTEGER,
                               core_minutes             INTEGER,
                               awake_minutes            INTEGER,
                               in_bed_minutes           INTEGER,
                               unspecified_minutes      INTEGER,
                               sample_count             INTEGER,                                        -- HealthKit raw 샘플 개수
                               night_hrv_ms             DOUBLE PRECISION,                               -- 야간 HRV 평균
                               weekly_hrv_baseline_ms   DOUBLE PRECISION,                               -- 직전 7일 HRV baseline
                               data_completeness        VARCHAR(20),                                    -- FULL | PARTIAL_STAGES | TOTAL_ONLY
                               raw_payload              JSONB,                                          -- HealthKit 원본 JSON
                               created_at               TIMESTAMPTZ       NOT NULL DEFAULT now(),
                               updated_at               TIMESTAMPTZ       NOT NULL DEFAULT now()
);

COMMENT ON TABLE  sleep_records IS '일자별 수면 데이터. (user_id, sleep_date) 유니크';
COMMENT ON COLUMN sleep_records.sleep_date         IS '수면이 종료된 날짜. 동일 사용자 동일 날짜는 갱신';
COMMENT ON COLUMN sleep_records.total_minutes      IS 'totalSleepMinutes (deep + rem + core)';
COMMENT ON COLUMN sleep_records.data_completeness  IS 'FULL: 단계별 데이터 모두 / PARTIAL_STAGES: 일부 단계 누락 / TOTAL_ONLY: 총 시간만';
COMMENT ON COLUMN sleep_records.raw_payload        IS 'HealthKit이 보낸 원본 페이로드 (재계산/분석 확장용)';


-- ─────────────────────────────────────────────────────────────────────────────
-- 7. pvt_sessions
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE pvt_sessions (
                              id                        BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id                   BIGINT            NOT NULL,
                              measurement_id            UUID              NOT NULL,                    -- iOS가 측정 시작 시 생성. idempotency 키
                              started_at                TIMESTAMPTZ       NOT NULL,
                              ended_at                  TIMESTAMPTZ       NOT NULL,
                              total_duration_ms         INTEGER           NOT NULL,
                              total_count               INTEGER           NOT NULL,                    -- 정상 측정 완료된 시도 수
                              raw_rt_ms                 INTEGER[]         NOT NULL,                    -- 원본 RT 배열 (ms)
                              corrected_rt_ms           INTEGER[]         NOT NULL,                    -- 기기별 보정 RT 배열 (ms)
                              avg_rt_ms                 DOUBLE PRECISION  NOT NULL,                    -- iOS 계산 평균 (lapse 제외)
                              median_rt_ms              DOUBLE PRECISION,
                              lapses                    INTEGER           NOT NULL,                    -- RT > 500ms 자극 수
                              is_valid                  BOOLEAN           NOT NULL,                    -- iOS 측 유효성 판정
                              invalid_reason            VARCHAR(50),
                              device_model_identifier   VARCHAR(50),                                   -- iPhone 모델 코드 (예: iPhone15,2)
                              device_model_group        VARCHAR(20),                                   -- IPHONE_PRO | IPHONE_STANDARD | IPHONE_SE
                              trials                    JSONB             NOT NULL DEFAULT '[]'::jsonb,
                              created_at                TIMESTAMPTZ       NOT NULL DEFAULT now()
);

COMMENT ON TABLE  pvt_sessions IS 'PVT(인지반응속도) 측정 세션';
COMMENT ON COLUMN pvt_sessions.measurement_id           IS 'iOS 측정 시작 시 발급. 동일 세션 중복 업로드 방지(idempotency)';
COMMENT ON COLUMN pvt_sessions.raw_rt_ms                IS '기기 터치 지연 보정 전 RT 배열';
COMMENT ON COLUMN pvt_sessions.corrected_rt_ms          IS 'device_model_group 기준 보정 후 RT 배열';
COMMENT ON COLUMN pvt_sessions.device_model_group       IS '터치 지연 보정 기준 그룹';
COMMENT ON COLUMN pvt_sessions.trials                   IS '자극별 raw/corrected RT 페어 배열';


-- ─────────────────────────────────────────────────────────────────────────────
-- 8. brain_roi_scores
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE brain_roi_scores (
                                  id                       BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id                  BIGINT            NOT NULL,
                                  session_id               BIGINT            NOT NULL,                     -- pvt_sessions.id
                                  sleep_id                 BIGINT            NOT NULL,                     -- sleep_records.id
                                  calculation_scenario     VARCHAR(20)       NOT NULL,                     -- A | B | C | D
                                  final_score              INTEGER           NOT NULL,                     -- 0-100
                                  sleep_score              INTEGER           NOT NULL,                     -- 0-100
                                  pvt_score                INTEGER           NOT NULL,                     -- 0-100
                                  quadrant                 VARCHAR(20)       NOT NULL,                     -- 추천 매칭 키
                                  formula_version          VARCHAR(20)       NOT NULL,                     -- 계산식 버전 (예: v1.0.0)
                                  breakdown                JSONB             NOT NULL DEFAULT '{}'::jsonb, -- 중간 계산 과정 전부
                                  measured_at              TIMESTAMPTZ       NOT NULL,
                                  created_at               TIMESTAMPTZ       NOT NULL DEFAULT now()
);

COMMENT ON TABLE  brain_roi_scores IS 'Brain ROI 점수 계산 결과';
COMMENT ON COLUMN brain_roi_scores.calculation_scenario IS '입력 데이터 조합에 따른 시나리오: A(둘 다 풍부) / B / C / D(최소)';
COMMENT ON COLUMN brain_roi_scores.quadrant             IS '사분면 분류. recommendations.quadrant_key 와 매칭';
COMMENT ON COLUMN brain_roi_scores.formula_version      IS '계산에 사용된 산식 버전. 메디컬 팀 산식 업데이트 시 변경';
COMMENT ON COLUMN brain_roi_scores.breakdown            IS '계산의 모든 중간값(JSON). 디버깅/문의 응대용';


-- ─────────────────────────────────────────────────────────────────────────────
-- 9. recommendations
--    NOTE: 원본 ERD 는 PK(id, roi_score_id) 복합키. 실용성을 검토했으나
--          외부에서 (id) 단독으로 참조할 수 있고 ORM 매핑이 단순해지므로
--          단일 PK(id) + roi_score_id UNIQUE 운영을 권장하나, 일단 ERD 충실히
--          복합 PK 로 유지. 추후 도메인 결정으로 V3 에서 변경 가능.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE recommendations (
                                 id               BIGINT      GENERATED BY DEFAULT AS IDENTITY,
                                 roi_score_id     BIGINT      NOT NULL,
                                 quadrant_key     VARCHAR(20) NOT NULL,                                   -- brain_roi_scores.quadrant 와 매칭
                                 title            VARCHAR(100) NOT NULL,
                                 message          TEXT        NOT NULL,
                                 suggested_tasks  JSONB       NOT NULL DEFAULT '[]'::jsonb,
                                 created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 PRIMARY KEY (id, roi_score_id)
);

COMMENT ON TABLE  recommendations IS 'Brain ROI 점수 기반 작업 추천';
COMMENT ON COLUMN recommendations.quadrant_key    IS '추천 매칭 키. brain_roi_scores.quadrant 와 동일 값';
COMMENT ON COLUMN recommendations.suggested_tasks IS 'iOS 가 카드 형태로 표시할 작업 리스트 (JSON Array)';